### ISSUE TITLE
Larger wallets not syncing anymore, any clearnet server

### ISSUE THREAD

**Issue by goodc0re** [Bertrand256/electrum-dash#7]
Since about July some larger wallets (wallet file size several MB) have not been able to sync at all. 
Now on version 4.1.7.1 and the problem continues. 

The server setting is set to "Select server automatically". Not using tor. No matter which server is connected, the connection indicator switches between syncing (blue arrows) and offline (red). The status message showing "Synchronizing... (0/X)". 

I tried opening wallets that only have one or two transactions (wallet file size 100-150 kb) and only those will sync. 

The history and coins tabs also stopped showing anything on the larger wallets, no data visible anymore. 

The wallets are using keys stored on Trezor One. The hardware wallet connection is working and the status icon is green.

**Comment by pshenmic** [comment]
Hey
I just deployed couple of servers, feel free to download a new version:
https://github.com/Bertrand256/electrum-dash/releases/tag/4.1.7.2

**Comment by pietrosperoni** [comment]
Hello
Hello @pshenmic thanks. I had the same problem. So I upgraded to 4.1.7.2. And it did not solve it. I am still stuck with Dash Electrum unable to connect. My latest transaction is from half of December. And at the time I had 4.1.7.1 and it was working fine. Now it is not connecting anymore.
Do we have a list of servers that we can connect to? 
I am trying 

dash-electrum.pshenmic.dev:50002

And it has a little asterisk after:

dash-electrum.pshenmic.dev:50002 *

Anything else I should try?

Thanks.
Pietro

**Comment by pshenmic** [comment]
Hey, @pietrosperoni 

Yeah, I just have spotted and reproduced that issue yesterday and I'm working on resolving this. I will let you know here soon

**Comment by pshenmic** [comment]
I raised some resource limits on my server `dash-electrum.pshenmic.dev:50002`, could you try once again?

I also found some more Dash Electrum server, you might want to take a chance there too
```
electrum1.cipig.net:20061
electrum2.cipig.net:20061
electrum3.cipig.net:20061
```

**Comment by pietrosperoni** [comment]
Hello, @pshenmic. 
Thank you very much. I do not keep that wallet on my normal computer, for security reasons, and I left the other in the office, so I cannot, right now. But as soon as possible I will and will report here, both in case it works and in case it does not.

I have no words to express my gratitude that someone is still keeping alive this project.

**Comment by pietrosperoni** [comment]
Hello @pshenmic , I finally could test it.
So far it is not working. Only on your server the system keeps connecting and disconnecting.
I then tried adding one by one the other Dash Electrum Servers electrum[1/2/3].cipig.net:20061
It meid a small weird change, while before it was connecting and disconnecting on your server as well, now it is always connected on your server, and it connects and disconnects on those other three. But still it is not syncronising. If you need me to make a small mp4 in which you see it I can do that in the next days.

**Comment by pshenmic** [comment]
How much addresses / transactions do you have in your wallet? If it is instantly disconnecting, then there is small chance that it is hitting resource limits (it would be disconnecting in the middle of the synchronization).

Do you receive masternode payouts with your wallet? If so, 4.1.7.2 version lacks support of v20 coinbase transactions and then it must be the issue.
Good for you, I have already resolved that in my repo fork, but not yet pulled in the changes to the upstream.
You can try this version, if that's the case https://github.com/pshenmic/electrum-dash/releases/tag/4.1.7.3-rc.30

PS:
I am currently working on a major Electrum Dash upgrade, which should bring upgrade all project dependencies, upgrade the whole project to the recent p2p protocols, and finally bringing working PrivateSend feature back. 

You can also hit me in the Discord, I'm answering all the time

**Comment by pietrosperoni** [comment]
As a raugh estimate I would say 
about 80 pages of 40 addresses each. So around 3200 adresses. 
And 21 pages of 27 transactions, so around 567 transactions. 
Is that too much? 😇

**Comment by pshenmic** [comment]
Thx, I will try to reproduce your case locally and 'll let you know 👍

**Comment by abdramane77** [comment]
https://github.com/Bertrand256/electrum-dash/issues/7
